name: deadsnakes
description: install (pre-release) pythons from deadsnakes
inputs:
  python-version:
    description: python version to use, such as '3.9'
    required: true
  debug:
    description: use debug version of python
    required: false
    default: false
  inside-container:
    description: if the action will run inside a container
    required: false
    default: false
runs:
  using: composite
  steps:
  - name: add deadsnakes ppa and install ${{ inputs.python-version }} ${{ inputs.debug == 'true' && '(debug)' || '' }}
    shell: bash
    run: |
      if [[ "${{ inputs.inside-container }}" == "false" ]]; then
        ${{ github.action_path }}/bin/install-python ${{ inputs.python-version }} ${{ inputs.debug == 'true' && '--debug' || '' }}
      else
        $GITHUB_ACTION_PATH/bin/install-python ${{ inputs.python-version }} ${{ inputs.debug == 'true' && '--debug' || '' }}
      fi