on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - {python: '3.7', debug: true, image: null}
        - {python: '3.11', debug: false, image: 'ubuntu:latest'}
        - {python: '3.11-dev', debug: false, image: null}
        - {python: '3.12-dev', debug: false, image: null}
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.
      with:
        python-version: ${{ matrix.python }}
        debug: ${{ matrix.debug }}
